databases:
  - name: sofia-db
    databaseName: sofia_db
    user: sofia
    plan: starter
    
services:
  - type: web
    name: sofia-backend
    runtime: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sofia-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.com
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    
  - type: web
    name: sofia-frontend
    runtime: static
    buildCommand: echo "No build needed"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
